In [24]:
import pandas as pd

from config import RAW_DIR, CLEAN_DB_PATH
from generate_data import main as generate_raw_data
from pipeline import (
    extract,
    clean_customers,
    clean_products,
    clean_orders,
    load_to_sqlite,
)

In [10]:
# Run this cell if you want to regenerate the random CSVs
generate_raw_data()
RAW_DIR

Generated 550 customers, 110 products, 1050 orders in C:\Users\Przemek\etl-pipeline\data\raw

WindowsPath('C:/Users/Przemek/etl-pipeline/data/raw')

In [25]:
raw_customers, raw_products, raw_orders = extract()

raw_customers.head()

,customer_id,first_name,last_name,email,phone,country,created_at
0,1,Daniel,Figueroa,jeffreydoyle@example.net,001-581-896-0013x3890,Cyprus,2025-07-13
1,2,Bridget,Pacheco,blakeerik@example.com,942-335-1161x55940,Uzbekistan,2025-02-15
2,3,Christian,Carter,barbara10@example.net,441.731.6475,Guinea,08-10-2025
3,4,Elizabeth,Miles,lynchgeorge@example.net,527.264.8350,Sri Lanka,2024-08-13
4,5,Richard,Jones,NaN,724.523.8849x696,Burundi,2024-11-04

In [26]:
raw_products.head()

   product_id    name         category   price currency  in_stock
0           1  Effect            Books  392.98      USD       273
1           2   Exist             Home  123.39      USD       462
2           3     Bed  Miscellaneous    418.38      USD       347
3           4    Over             Home  473.83      USD       236
4           5   Other             Home  385.87      USD       257

In [13]:
raw_orders.head()

,order_id,customer_id,product_id,order_date,status,quantity,unit_price,total_amount
0,1,349,11,2025-06-24,delivered,5,226.14,1130.70
1,2,58,118,2025-04-13,shipped,5,105.07,525.35
2,3,267,88,02-05-2025,cancelled,2,359.87,719.74
3,4,229,59,2025-04-20,cancelled,2,259.06,"518,12"
4,5,530,40,2025-12-18,pending,1,200.99,200.99

In [27]:
customers = clean_customers(raw_customers)

customers.head()

c:\Users\Przemek\etl-pipeline\pipeline.py:32: UserWarning: Parsing dates in %Y-%m-%d format when dayfirst=True was specified. Pass `dayfirst=False` or specify a format to silence this warning.
  "United States of America": "US",

,customer_id,first_name,last_name,email,phone,country,created_at
0,1,Daniel,Figueroa,jeffreydoyle@example.net,001-581-896-0013x3890,Cyprus,2025-07-13
1,2,Bridget,Pacheco,blakeerik@example.com,942-335-1161x55940,Uzbekistan,2025-02-15
2,3,Christian,Carter,barbara10@example.net,441.731.6475,Guinea,NaN
3,4,Elizabeth,Miles,lynchgeorge@example.net,527.264.8350,Sri Lanka,2024-08-13
6,7,Eric,Smith,teresa28@example.org,+1-948-293-2528x8095,Bouvet Island (Bouvetoya),2025-02-04

In [28]:
products = clean_products(raw_products)

products.head()

   product_id    name       category   price currency  in_stock
0           1  Effect          Books  392.98      USD       273
1           2   Exist           Home  123.39      USD       462
2           3     Bed  Miscellaneous  418.38      USD       347
3           4    Over           Home  473.83      USD       236
4           5   Other           Home  385.87      USD       257

In [29]:
orders = clean_orders(raw_orders, customers=customers, products=products)

orders.head()

c:\Users\Przemek\etl-pipeline\pipeline.py:91: UserWarning: Parsing dates in %Y-%m-%d format when dayfirst=True was specified. Pass `dayfirst=False` or specify a format to silence this warning.

,order_id,customer_id,product_id,order_date,status,quantity,unit_price,total_amount
0,1,349,11,2025-06-24,delivered,5,226.14,1130.70
3,4,229,59,2025-04-20,cancelled,2,259.06,518.12
5,6,24,90,2025-06-24,pending,1,272.88,272.88
7,8,196,49,2025-09-12,shipped,4,44.72,178.88
9,10,153,93,2025-03-06,cancelled,5,214.94,1074.70

In [30]:
load_to_sqlite(customers, products, orders)
CLEAN_DB_PATH

WindowsPath('C:/Users/Przemek/etl-pipeline/cleaned.db')

In [31]:
import sqlite3

conn = sqlite3.connect(CLEAN_DB_PATH)

In [39]:

pd.read_sql("SELECT * FROM customers", conn).head(50)

,customer_id,first_name,last_name,email,phone,country,created_at
0,1,Daniel,Figueroa,jeffreydoyle@example.net,+15818960013,Cyprus,2025-07-13
1,2,Bridget,Pacheco,blakeerik@example.com,NaN,Uzbekistan,2025-02-15
2,3,Christian,Carter,barbara10@example.net,NaN,Guinea,NaN
3,4,Elizabeth,Miles,lynchgeorge@example.net,NaN,Sri Lanka,2024-08-13
4,7,Eric,Smith,teresa28@example.org,+19482932528,Bouvet Island (Bouvetoya),2025-02-04
5,8,Michael,Galloway,john39@example.org,NaN,Croatia,2026-02-23
6,9,Amber,Blair,jenniferross@example.net,+15575871331,Albania,2026-02-23
7,10,Jean,Brown,whiteheadmichele@example.org,NaN,Palestinian Territory,2024-04-28
8,11,Michael,Jenkins,nuneztracey@example.org,NaN,Cocos (Keeling) Islands,2025-02-01
9,12,Steven,Baxter,ramosmichelle@example.net,NaN,Tonga,NaN
10,13,Rachel,Martin,gallowayjoseph@example.com,NaN,Myanmar,2025-01-09
11,14,Wesley,Farrell,brianromero@example.org,NaN,Italy,NaN
12,15,Brandy,Mills,james53@example.com,NaN,Bulgaria,NaN
13,16,Michael,Jones,mikemoore@example.net,NaN,Finland,NaN
14,17,Jason,Cooper,william40@example.org,NaN,Belarus,NaN
15,18,Hannah,Hernandez,davenportbrandi@example.org,NaN,Tonga,2026-01-18
16,20,Raymond,Ramirez,rasmussenjoshua@example.net,NaN,Jordan,NaN
17,21,Tracey,Wilson,jonathanfletcher@example.org,NaN,Qatar,NaN
18,22,Angela,Lee,lbyrd@example.net,NaN,Kenya,2024-10-19
19,23,Emma,Dixon,donnacampbell@example.net,NaN,Israel,2025-02-10
20,24,Crystal,Lee,psnyder@example.org,+14019632870,Papua New Guinea,2026-01-21
21,25,Vanessa,Larson,usalazar@example.net,NaN,Dominica,NaN
22,26,Matthew,Orozco,taylorjesse@example.net,NaN,Syrian Arab Republic,2024-10-01
23,27,Perry,Carrillo,gateskathy@example.com,NaN,Antarctica (the territory South of 60 deg S),2025-01-24
24,28,Matthew,Shelton,dramsey@example.org,NaN,Hong Kong,2024-12-31
25,29,Jason,Murphy,aramirez@example.com,NaN,Cook Islands,2024-11-13
26,30,Andrew,Hernandez,thomaswilson@example.org,+626458299124,Indonesia,2025-12-15
27,34,Jennifer,Freeman,hannahbrewer@example.com,NaN,Samoa,2024-09-07
28,36,Kenneth,Ward,alexis82@example.com,NaN,Lesotho,NaN
29,37,Matthew,Sheppard,shelley71@example.org,NaN,Singapore,2025-02-09
30,38,Omar,Kerr,michelle64@example.net,+13094133412,Afghanistan,2025-04-13
31,39,Shannon,Wheeler,antonio44@example.net,+14133493618,Bahamas,NaN
32,40,Laura,Larson,scott74@example.net,NaN,Denmark,2024-07-10
33,41,Mary,Johnston,keyemily@example.com,NaN,Bermuda,2025-08-09
34,42,Michael,Cook,hodgemark@example.net,NaN,Isle of Man,2025-03-04
35,43,Jacob,Cox,wgarrett@example.org,NaN,Georgia,NaN
36,44,Alexander,Russell,victoriadurham@example.com,NaN,Micronesia,2025-05-05
37,45,Patrick,Weeks,michellehill@example.com,NaN,Korea,NaN
38,46,Marc,Lopez,ashleyhall@example.com,NaN,Tunisia,NaN
39,47,Scott,Fox,jsmith@example.com,NaN,Niger,NaN
40,49,Laura,Jackson,lynchpatrick@example.net,NaN,United Arab Emirates,2025-08-15
41,50,Erica,Moore,llandry@example.com,NaN,Angola,2024-10-13
42,51,Dominique,Hill,lozanojulie@example.com,NaN,Bermuda,2025-12-08
43,52,Kenneth,Burgess,jamesbuchanan@example.com,NaN,Somalia,2026-02-08
44,53,Alexander,Herrera,vrichardson@example.net,NaN,North Macedonia,2025-01-04
45,54,Steven,Haynes,cwilson@example.org,NaN,Palau,2025-12-03
46,55,Martha,Gilbert,antonio53@example.com,NaN,Panama,2024-05-19
47,56,Darlene,Harper,williamsmatthew@example.org,+14312839335,Falkland Islands (Malvinas),2024-08-15
48,57,Tracey,Huerta,lauren10@example.org,NaN,Malta,2025-12-30
49,58,Julie,Alvarez,william17@example.net,NaN,Poland,2024-05-31